### PR TITLE
Add new functionalities and French translation

### PR DESCRIPTION
**Pull request by nanego**
Please find in this Pull Request a new French locale file.
I have also updated the English translation.

### CODE REVIEW

**Comment by nanego** [comment]
capture_issue_closer

With these updates, the plugin now allows the selection of several initial statuses.
A note is also added to the issue and the journal shows when the change has been done.

**Comment by nosmicek** [comment]
Tested on our Redmine instalation, ver 3.4.6, so far no problems.

Could you make it more universal? We need more than just close the issue, we need to automate more issue status changes from status A to status B after period 1, from C to D after period 2, where status B and D is not everytime a closed issue status. 
So i basically file "cloned" plugin into issuecloser2 and installed second instance of issuecloser (litle modified) to our redmine installation just to have another posibility to define automatic issue status change. 

Couldn't find any other plugin, that does automatic status change after period of time.

Thanks for the work so far.

**Comment by nosmicek** [comment]
ok, i found one small bug, in rake task iclose, there is a limit(1) clause, that limits number of automatically closed tasks to exactly 1 per rake task run. that is nonsense.

>      issues_to_change = Issue.where(status_id: Setting.plugin_issuecloser['issues_status_from'])
>                              .where("updated_on < ?", Setting.plugin_issuecloser['auto_close_after_days'].to_i.days.ago)
>                              .order(updated_on: :asc)
>                              .limit(1)
>

deleting the .limit(1) line will run the task on all issues matching criteria.

**Comment by nanego** [comment]
You are right. I must have forgotten to delete it after my last tests.

**Pull request merged**
